"""empty message

Revision ID: dc24bd184413
Revises: a5cffa318ac2
Create Date: 2025-04-26 09:12:25.811932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc24bd184413'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('climate', sa.String(length=32), nullable=True),
    sa.Column('diameter', sa.String(length=16), nullable=True),
    sa.Column('gravity', sa.String(length=8), nullable=True),
    sa.Column('orbital_period', sa.String(length=8), nullable=True),
    sa.Column('population', sa.String(length=16), nullable=True),
    sa.Column('rotation_period', sa.String(length=8), nullable=True),
    sa.Column('surface_water', sa.String(length=3), nullable=True),
    sa.Column('terrain', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('birth_year', sa.String(length=32), nullable=True),
    sa.Column('eye_color', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('hair_color', sa.String(length=32), nullable=True),
    sa.Column('height', sa.String(length=8), nullable=True),
    sa.Column('mass', sa.String(length=32), nullable=True),
    sa.Column('homeworld', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeworld'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('people')
    op.drop_table('planets')
    # ### end Alembic commands ###
